Fixes missing parameters for InlineHstoreList
test_hstore:

 >           assert rv.status_code ==
 E           assert  ==
 E            +  where  = <WrapperTestResponse streamed [ INTERNAL SERVER ERROR]>.status_code

   File "/home/runner/work/flask-admin/flask-admin/.tox/py/lib/python3.11/site-packages/wtforms/form.py", line 127, in process
     field.process(formdata, data, extra_filters=field_extra_filters)
 TypeError: InlineHstoreList.process() got an unexpected keyword argument 'extra_filters'

WTForms 3 form.BaseForm.process() takes an extra_filters parameter