Test the minimum requirements
With monogengine 0.19.1:
error in mongoengine setup command: use_2to3 is invalid.

jinja2 2.10.1 needed for flask 1.1.1

itsdangerous==2.0.1 else:
ImportError: cannot import name 'json' from 'itsdangerous'

werkzeug else:
ImportError: cannot import name 'BaseResponse' from 'werkzeug.wrappers'

Minimum version of Pillow raised in:
ecdc3e91 ("Require Pillow >= 9.1.0", 2023-10-15)