Fix Exception: Cannot find reverse relation for model
SQLAlchemy 2.0.2 removed the invocation of registry.configure() from
Mapper.iterate_properties causing this problem.

sqlalchemy.orm.registry.configure() was added in 1.4.0b2.

Using SQLAlchemy 1.4 requires SQLAlchemy-Utils >= 0.37.0 else:
ImportError: cannot import name '_ColumnEntity' from 'sqlalchemy.orm.query'

Observed as test failures in:

flask_admin/tests/sqla/test_basic.py
flask_admin/tests/sqla/test_form_rules.py
flask_admin/tests/sqla/test_inlineform.py