Restrict Flask to 2.0.0 in testing
AssertionError: The setup method 'register_blueprint' can no longer be
called on the application.

https://github.com/pallets/flask/issues/4786